// es/packages/input/src/input.jsx
import * as tslib_1 from "tslib";
import Vue from 'vue';
import Component from 'vue-class-component';
import { Prop, Watch } from 'vue-property-decorator';
let Input = class Input extends Vue {
    constructor() {
        super(...arguments);
        this.currentValue = this.value || '';
    }
    valueChanged(value) {
        this.currentValue = value;
    }
    get inputRef() {
        return this.$refs['input'];
    }
    onInputBlur(e) {
        const value = e.target.value;
        this.$emit('blur', value);
    }
    onInputFocus(e) {
        this.$emit('focus');
    }
    focus() {
        if (this.inputRef) {
            this.inputRef.focus();
        }
    }
    render() {
        const value = this.currentValue + '';
        const type = this.type === 'number' ? 'text' : this.type;
        return <input value={value} ref={'input'} type={type} disabled={this.disabled} readonly={this.readonly} placeholder={this.placeholder} onblur={(e) => {
            this.onInputBlur(e);
        }} style={{ textAlign: this.textAlign }} {...this.$props} {...this.$attrs} oninput={e => {
            this.$emit('change', e);
        }}/>;
    }
};
tslib_1.__decorate([
    Prop({ type: [String, Number] })
], Input.prototype, "value", void 0);
tslib_1.__decorate([
    Prop(Boolean)
], Input.prototype, "disabled", void 0);
tslib_1.__decorate([
    Prop(String)
], Input.prototype, "placeholder", void 0);
tslib_1.__decorate([
    Prop(Boolean)
], Input.prototype, "readonly", void 0);
tslib_1.__decorate([
    Prop({ type: String })
], Input.prototype, "type", void 0);
tslib_1.__decorate([
    Prop({ type: String, default: 'left' })
], Input.prototype, "textAlign", void 0);
tslib_1.__decorate([
    Watch('value')
], Input.prototype, "valueChanged", null);
Input = tslib_1.__decorate([
    Component({
        name: 'Input'
    })
], Input);
export default Input;
//# sourceMappingURL=input.jsx.map

// src/packages/input/src/input.tsx
import {Options, Vue} from 'vue-class-component';

@Options({
  name: 'Input',
  props: {
    value: {type: [String, Number]},
    disabled: Boolean,
    placeholder: String,
    readonly: Boolean,
    type: {type: String},
    textAlign: {type: String, default: 'left'}
  },
  watch: {
    value(value: string) {
      this.currentValue = value;
    }
  }
})

class Input extends Vue {
  public value: string;
  public disabled: boolean;
  public placeholder: string;
  public readonly: boolean;
  public type: string;
  private currentValue: string = this.value || '';
  private textAlign: 'left' | 'right' | 'center';

  get inputRef(): HTMLInputElement {
    return this.$refs['input'] as HTMLInputElement;
  }

  public onInputBlur(e) {
    const value = (e.target as any).value;
    this.$emit('blur', value);
  }

  public onInputFocus(e) {
    this.$emit('focus');
  }

  public focus() {
    if (this.inputRef) {
      this.inputRef.focus();
    }
  }

  public render(): any {
    const value = this.currentValue + '';
    const type = this.type === 'number' ? 'text' : this.type;
    const props: any = {
      value,type,
      ref: 'input',
      disabled: this.disabled,
      readonly: this.readonly,
      placeholder: this.placeholder,
      onBlur: (e) => {
        this.onInputBlur(e);
      },
      onInput: e => {
        this.$emit('change', e);
      },
      style: {textAlign: this.textAlign},
      ...this.$props,
      ...this.$attrs
    }
    return <input {...props}/>;
  }
}

export default Input as any;
