// src/packages/input/src/input.tsx
import {Options, Vue} from 'vue-class-component';

@Options({
  name: 'Input',
  props: {
    value: {type: [String, Number]},
    disabled: Boolean,
    placeholder: String,
    readonly: Boolean,
    type: {type: String},
    textAlign: {type: String, default: 'left'}
  },
  watch: {
    value(value: string) {
      this.currentValue = value;
    }
  }
})

class Input extends Vue {
  public value: string;
  public disabled: boolean;
  public placeholder: string;
  public readonly: boolean;
  public type: string;
  private currentValue: string = this.value || '';
  private textAlign: 'left' | 'right' | 'center';

  get inputRef(): HTMLInputElement {
    return this.$refs['input'] as HTMLInputElement;
  }

  public onInputBlur(e) {
    const value = (e.target as any).value;
    this.$emit('blur', value);
  }

  public onInputFocus(e) {
    this.$emit('focus');
  }

  public focus() {
    if (this.inputRef) {
      this.inputRef.focus();
    }
  }

  public render(): any {
    const value = this.currentValue + '';
    const type = this.type === 'number' ? 'text' : this.type;
    const props: any = {
      value,type,
      ref: 'input',
      disabled: this.disabled,
      readonly: this.readonly,
      placeholder: this.placeholder,
      onBlur: (e) => {
        this.onInputBlur(e);
      },
      onInput: e => {
        this.$emit('change', e);
      },
      style: {textAlign: this.textAlign},
      ...this.$props,
      ...this.$attrs
    }
    return <input {...props}/>;
  }
}

export default Input as any;

// src/packages/input/src/input.jsx
import { defineComponent, ref, watch } from 'vue';
const Input = defineComponent({
    name: 'Input',
    props: {
        value: { type: [String, Number] },
        disabled: Boolean,
        placeholder: String,
        readonly: Boolean,
        type: { type: String },
        textAlign: { type: String, default: 'left' }
    },
    setup(props, { emit }) {
        var _a, _b;
        const currentValue = ref((_b = (_a = props.value) === null || _a === void 0 ? void 0 : _a.toString()) !== null && _b !== void 0 ? _b : '');
        const inputRef = ref(null);
        const onInputBlur = (e) => {
            const value = e.target.value;
            emit('blur', value);
        };
        const onInputFocus = (e) => {
            emit('focus');
        };
        const focus = () => {
            if (inputRef.value) {
                inputRef.value.focus();
            }
        };
        watch(() => props.value, (value) => {
            currentValue.value = value === null || value === void 0 ? void 0 : value.toString();
        });
        return { currentValue, inputRef, onInputBlur, focus, onInputFocus };
    },
    render() {
        const { currentValue } = this;
        const type = this.type === 'number' ? 'text' : this.type;
        const props = Object.assign(Object.assign(Object.assign({}, this.$props), this.$attrs), { value: currentValue, type, ref: (el) => {
                this.inputRef = el;
            }, disabled: this.disabled, readonly: this.readonly, placeholder: this.placeholder, onBlur: (e) => {
                this.onInputBlur(e);
            }, onInput: e => {
                this.$emit('change', e);
            }, style: { textAlign: this.textAlign } });
        return <input {...props}/>;
    }
});
export default Input;
//# sourceMappingURL=input.jsx.map
